package com.shawndfox.numberconverter;

import javax.swing.JOptionPane;

/**
 * An implementation of a JFrame interface which is the primary user interface
 * frame of the application.  This class implements the entry point of the 
 * application.
 * 
 * @author Shawn D. Fox
 */
public class NumberConverter extends javax.swing.JFrame {

   /**
    * Creates new form NumberConverter
    */
   public NumberConverter() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();
      jButton6 = new javax.swing.JButton();
      labelEnteredValue = new javax.swing.JLabel();
      labelConvertedValue = new javax.swing.JLabel();
      enteredValue = new javax.swing.JLabel();
      convertedValue = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Number Converter");

      jButton1.setText("Bin to Dec");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            convertBinaryToDecimal(evt);
         }
      });

      jButton2.setText("Bin to Hex");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            convertBinaryToHexadecimal(evt);
         }
      });

      jButton3.setText("Dec to Bin");
      jButton3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            convertDecimalToBinary(evt);
         }
      });

      jButton4.setText("Dec to Hex");
      jButton4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            convertDecimalToHexadecimal(evt);
         }
      });

      jButton5.setText("Hex to Bin");
      jButton5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            convertHexadecimalToBinary(evt);
         }
      });

      jButton6.setText("Hex to Dec");
      jButton6.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            convertHexadecimaltoDecimal(evt);
         }
      });

      labelEnteredValue.setText("Input:");

      labelConvertedValue.setText("Converted Value: ");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jButton1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jButton4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton6))
               .addGroup(layout.createSequentialGroup()
                  .addGap(80, 80, 80)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(labelConvertedValue)
                     .addComponent(labelEnteredValue))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(enteredValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(convertedValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton1)
               .addComponent(jButton2)
               .addComponent(jButton3)
               .addComponent(jButton4)
               .addComponent(jButton5)
               .addComponent(jButton6))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(labelEnteredValue)
               .addComponent(enteredValue))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(labelConvertedValue)
               .addComponent(convertedValue))
            .addContainerGap(13, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * Convert the number entered by the user from Decimal into Binary after validating the input.
    * @param evt - not used
    */
   private void convertDecimalToBinary(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertDecimalToBinary
      String inputValue = JOptionPane.showInputDialog("Please enter a Decimal value");
      
      if(FromDecimal.validate(inputValue)) {
         labelEnteredValue.setText("Decimal");
         enteredValue.setText(inputValue);
         labelConvertedValue.setText("Binary");
         convertedValue.setText(FromDecimal.toBinary(inputValue));
      }
      else {
         JOptionPane.showMessageDialog(
            null, 
            "The only characters allowed are 0-9", 
            "Invalid Entry!", 
            JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_convertDecimalToBinary

   /**
    * Convert the number entered by the user from binary into hexadecimal after validating the input.
    * @param evt - not used
    */
   private void convertBinaryToHexadecimal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBinaryToHexadecimal
      String inputValue = JOptionPane.showInputDialog("Please enter a Binary value");
      
      if(FromBinary.validate(inputValue)) {
         labelEnteredValue.setText("Binary");
         enteredValue.setText(inputValue);
         labelConvertedValue.setText("Hexadecimal");
         convertedValue.setText(FromBinary.toHexaDecimal(inputValue));
      }
      else {
         JOptionPane.showMessageDialog(
            null, 
            "The only numeric characters allowed are 0-1",  
            "Invalid Entry!", 
            JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_convertBinaryToHexadecimal

   /**
    * Convert the number entered by the user from binary into decimal after validating the input.
    * @param evt - not used
    */
   private void convertBinaryToDecimal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBinaryToDecimal
      String inputValue = JOptionPane.showInputDialog("Please enter a Binary value");
      
      if(FromBinary.validate(inputValue)) {
         labelEnteredValue.setText("Binary");
         enteredValue.setText(inputValue);
         labelConvertedValue.setText("Decimal");
         convertedValue.setText(FromBinary.toDecimal(inputValue));
      }
      else {
         JOptionPane.showMessageDialog(
            null, 
            "The only numeric characters allowed are 0-1", 
            "Invalid Entry!", 
            JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_convertBinaryToDecimal

   /**
    * Convert the number entered by the user from decimal into hexadecimal after validating the input.
    * @param evt - not used
    */
   private void convertDecimalToHexadecimal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertDecimalToHexadecimal
      String inputValue = JOptionPane.showInputDialog("Please enter a Decimal value");
      
      if(FromDecimal.validate(inputValue)) {
         labelEnteredValue.setText("Decimal");
         enteredValue.setText(inputValue);
         labelConvertedValue.setText("Hexadecimal");
         convertedValue.setText(FromDecimal.toHexadecimal(inputValue.toUpperCase()));
      }
      else {
         JOptionPane.showMessageDialog(
            null, 
            "The only characters allowed are 0-9", 
            "Invalid Entry!", 
            JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_convertDecimalToHexadecimal

   /**
    * Convert the number entered by the user from hexadecimal into binary after validating the input.
    * @param evt - not used
    */
   private void convertHexadecimalToBinary(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertHexadecimalToBinary
      String inputValue = JOptionPane.showInputDialog("Please enter a Hexadecimal value");
      if(FromHexadecimal.validate(inputValue)) {
         labelEnteredValue.setText("Hexadecimal");
         enteredValue.setText(inputValue);
         labelConvertedValue.setText("Binary");
         convertedValue.setText(FromHexadecimal.toBinary(inputValue.toUpperCase()));
      }
      else {
         JOptionPane.showMessageDialog(
            null, 
            "The only characters allowed are a-f A-F or 0-9", 
            "Invalid Entry!", 
            JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_convertHexadecimalToBinary
    
   /**
    * Convert the number entered by the user from hexadecimal into decimal after validating the input.
    * @param evt - not used
    */
   private void convertHexadecimaltoDecimal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertHexadecimaltoDecimal
      String inputValue = JOptionPane.showInputDialog("Please enter a Hexadecimal value");
      if(FromHexadecimal.validate(inputValue)) {
         labelEnteredValue.setText("Hexadecimal");
         enteredValue.setText(inputValue);
         labelConvertedValue.setText("Decimal");
         convertedValue.setText(FromHexadecimal.toDecimal(inputValue.toUpperCase()));
      }
      else {
         JOptionPane.showMessageDialog(
            null, 
            "The only characters allowed are a-f A-F or 0-9", 
            "Invalid Entry!", 
            JOptionPane.ERROR_MESSAGE);
      }
   }//GEN-LAST:event_convertHexadecimaltoDecimal

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(NumberConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(NumberConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(NumberConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(NumberConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new NumberConverter().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel convertedValue;
   private javax.swing.JLabel enteredValue;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JButton jButton6;
   private javax.swing.JLabel labelConvertedValue;
   private javax.swing.JLabel labelEnteredValue;
   // End of variables declaration//GEN-END:variables
}
