
package GuestBook;

import java.awt.event.ActionListener;

/**
 * The ContactBookView builds the GUI components to be presented to the user.
 * 
 * @author Shawn D. Fox
 */
public class ContactBookView extends javax.swing.JFrame {

   /**
    * Creates new form ContactBookView
    */
   public ContactBookView() {
      initComponents();
   }
   
   /**
    * Registers an implementation of the ActionListener interface that will
    * handle the submit contact button press.
    * 
    * @param listener 
    */
   public void registerSubmitContactListener(ActionListener listener) {
      if(listener == null) {
         throw new NullPointerException();
      }
      
      submitContactButton.addActionListener(listener);
   }
   
   /**
    * Clears all text in the data entry text fields.
    * 
    */
   public void clearContactInformation() {
      firstNameText.setText("");
      lastNameText.setText("");
      addressText.setText("");
      phoneText.setText("");
   }
   
   /**
    * Inserts all current contact information into the contacts text area.
    * 
    * @param contacts 
    */
   public void refreshContacts(String contacts) {
      allContactsTextArea.setText(contacts);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      contactEntryPanel = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      firstNameLabel = new javax.swing.JLabel();
      firstNameText = new javax.swing.JTextField();
      lastNameLabel = new javax.swing.JLabel();
      lastNameText = new javax.swing.JTextField();
      addressLabel = new javax.swing.JLabel();
      addressText = new javax.swing.JTextField();
      phoneLabel = new javax.swing.JLabel();
      phoneText = new javax.swing.JTextField();
      jPanel3 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      allContactsTextArea = new javax.swing.JTextArea();
      jPanel5 = new javax.swing.JPanel();
      submitContactButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Contact Book");
      setResizable(false);

      jPanel2.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

      firstNameLabel.setText("First Name");
      jPanel2.add(firstNameLabel);
      jPanel2.add(firstNameText);

      lastNameLabel.setText("Last Name");
      jPanel2.add(lastNameLabel);
      jPanel2.add(lastNameText);

      addressLabel.setText("Address");
      jPanel2.add(addressLabel);
      jPanel2.add(addressText);

      phoneLabel.setText("Phone");
      phoneLabel.setName(""); // NOI18N
      jPanel2.add(phoneLabel);
      jPanel2.add(phoneText);

      allContactsTextArea.setEditable(false);
      allContactsTextArea.setColumns(15);
      allContactsTextArea.setRows(5);
      jScrollPane1.setViewportView(allContactsTextArea);

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );

      submitContactButton.setText("Submit");
      submitContactButton.setToolTipText("Store the contact to the contact book");

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(91, 91, 91)
            .addComponent(submitContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(85, Short.MAX_VALUE))
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addContainerGap(14, Short.MAX_VALUE)
            .addComponent(submitContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );

      javax.swing.GroupLayout contactEntryPanelLayout = new javax.swing.GroupLayout(contactEntryPanel);
      contactEntryPanel.setLayout(contactEntryPanelLayout);
      contactEntryPanelLayout.setHorizontalGroup(
         contactEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(contactEntryPanelLayout.createSequentialGroup()
            .addGroup(contactEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(contactEntryPanelLayout.createSequentialGroup()
                  .addGap(75, 75, 75)
                  .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE))
               .addGroup(contactEntryPanelLayout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      contactEntryPanelLayout.setVerticalGroup(
         contactEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(contactEntryPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(contactEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(contactEntryPanelLayout.createSequentialGroup()
                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(28, 28, 28)
                  .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(contactEntryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(contactEntryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(17, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel addressLabel;
   private javax.swing.JTextField addressText;
   private javax.swing.JTextArea allContactsTextArea;
   private javax.swing.JPanel contactEntryPanel;
   private javax.swing.JLabel firstNameLabel;
   private javax.swing.JTextField firstNameText;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JLabel lastNameLabel;
   private javax.swing.JTextField lastNameText;
   private javax.swing.JLabel phoneLabel;
   private javax.swing.JTextField phoneText;
   private javax.swing.JButton submitContactButton;
   // End of variables declaration//GEN-END:variables

   /**
    * @return the addressText
    */
   public String getAddressText() {
      return addressText.getText();
   }

   /**
    * @return the firstNameText
    */
   public String getFirstNameText() {
      return firstNameText.getText();
   }

   /**
    * @return the lastNameText
    */
   public String getLastNameText() {
      return lastNameText.getText();
   }

   /**
    * @return the phoneText
    */
   public String getPhoneText() {
      return phoneText.getText();
   }
}
